### ISSUE TITLE
This library should have way more stars! 🥇 

### ISSUE THREAD

**Issue by jln-dk** [betula/use-between#14]
Hey @betula , just wanted to say thank you for this awesome library! ✋ 
Switching from React Context + useReducer to this library reduced soooo much boilerplate code.
It's much more nice, clean and simple now, plus the bonus of using "useEffect" incapsulated within the state hook is just awesome.

I don't get why this library doesn't have more stars and more popularity. People using useContext+useReducer are really missing out 😃 

Thanks!

/ Jesper

**Comment by betula** [comment]
Hi Jesper!

Thank you heartily for the warmth of your words. I am very glad that the library finds its application and brings ease to development, abstraction, and code! 🥰 

Happy coding 🤗

**Comment by loia5tqd001** [comment]
Have you encountered any difficulties from then @jln-dk ? I've tried and it works pretty well in simple cases. However when working with react-router, when the page is unmounted, the state seems to be lost as well.
For example:
Page A has `aBooleanState = true` by default. If I'm in page A, toggle `aBooleanState to false`, then go to page B. When come back to page A I expect `aBooleanState` to persist the `false` value. But it's `true` which is the default.

**Comment by loia5tqd001** [comment]
[Here](https://codesandbox.io/s/react-router-forked-5917o) is the codesandbox to reproduce the problem I stated above. @betula

**Comment by betula** [comment]
Hi @loia5tqd001,
Nice catch! Thanks!:+1:
I will take it.

And it will be great if you can move it into a [new issue](https://github.com/betula/use-between/issues/new). The description of the problem and a link to reproduce on the codesandbox (special thanks for that!).

**Comment by melloware** [comment]
I could not agree more.  This library makes working with React a joy rather than a pain and it rids my need for Redux.

**Comment by ronster37** [comment]
I was about to install Redux until I found this library and it is a live saver. Really awesome job @betula. I don't know if I ever need to use Redux again haha
