### ISSUE TITLE
Send mail to facebook team)

### ISSUE THREAD

**Issue by betula** [betula/use-between#2]

**Comment by loia5tqd001** [comment]
What did happen with this, sir @betula . If the React team can support this out of the box, it would be life-saver for a lot of us.

**Comment by loia5tqd001** [comment]
I mean the API of this library is definitely the best so far I've seen. It's so simple. But under the hood, it strongly relies on React's internal implementation, which is not stable and reliable enough to put into production IMO, as their internal implementation might change anytime without our notice.

**Comment by betula** [comment]
I confess I did not find anyone to whom I could write personally.

I wrote about the library in the comments to the official video on Facebook Recoil, in the hope that they would pay attention to me, but the comment was deleted.
And Dan Abramov isn't responding on Twitter either)

It will be cool if you try to write to someone! Of course, if you have time for It.
