### ISSUE TITLE
Preact support

### ISSUE THREAD

**Issue by dave-irvine** [betula/use-between#24]
This is probably unlikely due to how this library uses internal React features, but I was wondering if it would be possible to add Preact support?

Currently it doesn't seem to work :( https://codesandbox.io/s/relaxed-sunset-u2omw

**Comment by betula** [comment]
Hi Dave!

Thank you very much for your interest, but only React is supported at the moment. 
You can use Preact Compat with Webpack aliases, but then you won't be able to use pure CRA.

I'm sure one day we'll figure out how to use it together with Preact!

**Comment by dave-irvine** [comment]
Hmm I am running Compat, but I couldn't make it work. No worries I will find another way :)
