### ISSUE TITLE
Using hooks with props

### ISSUE THREAD

**Issue by Jonhyfun** [betula/use-between#29]
Does usebetween work properly if i have a hook that recieves props?

Eslinter complains i cant use a hook inside a callback and there are no examples in the documentation.

I tried using it like `(props) => useBetween((props) => useLayoutModalsBase(props))` and it doesnt work, i believe it might be because that creates a new hook instance everytime i call it

**Comment by betula** [comment]
Hello!
Exists two different logic in that case:

https://github.com/betula/use-between/issues/15#issuecomment-894324450

**Comment by Jonhyfun** [comment]
I see, thank you
