### ISSUE TITLE
React 18 Strict Mode

### ISSUE THREAD

**Issue by melloware** [betula/use-between#33]
@betula have you tested with React 18 yet?  One of my devs is reporting its not working to update values in React 18.

I haven't drilled into it yet but wanted to see if you have tested on 18?

**Comment by melloware** [comment]
Here is a code sandbox reproducer showing you the updates aren't happening: https://codesandbox.io/s/todos-use-bettwen-forked-z05bcw?file=/src/index.js

**Comment by melloware** [comment]
OK I updated to React 18.1.0 and removed `<StrictMode>` and it works.

https://codesandbox.io/s/todos-use-bettwen-forked-5r2ycf?file=/src/index.js

**Comment by MoonLiightz** [comment]
I have run into the same problem. With Strict Mode enabled in React 18, there is no respective `useEffect` triggered.

**Comment by melloware** [comment]
For now I have had to disable StrictMode to make my app work.  I think its something to do with the new Strict Mode does a `mount...unmount... mount with previous` to make sure all components can handle future React Concurrent or something like that.  Hopefully @betula can figure it out!

**Comment by betula** [comment]
Hello @melloware,

I looked, I understood. The reason for the behavior is the double call of functional components in Strict Mode. Thank you very much for such a great problem finding!

I'll fix it in the next couple of weeks. Will be soon.

Thank you all for your activity on the project!

**Comment by melloware** [comment]
You rock!

**Comment by betula** [comment]
Hello Guys!
@melloware, and @MoonLiightz

Great news! I made some changes and now Strict Mode works.

https://codesandbox.io/s/todos-use-bettwen-forked-fonshg?file=/src/index.js

Feel free to try and give your feedback!

[Release 1.3.4](https://github.com/betula/use-between/discussions/35)

Enjoy and 
Happy Coding)

**Comment by melloware** [comment]
@betula that is great news!  We will update and let you know how it goes.
